#!/usr/bin/tclsh

# Random number with normal distribution
# https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform
proc nrand {} {
  return  [expr sqrt(-2.0 * log(rand()))*cos(2*3.1415926*rand())]
}

set x 0
for {set i 0} {$i<200} {incr i} {
  incr x
  set y [expr sin(2*3.1415926*$x/100)]
  puts "$x $y"
}

for {set i 0} {$i<200} {incr i} {
  incr x
  set r [nrand]
  set y [expr sin(2*3.1415926*$x/100) + 0.3*$i/200*$r]
  puts "$x $y"
}

for {set i 0} {$i<100} {incr i} {
  incr x
  puts "$x [expr 0.3*[nrand]]"
}

for {set i 0} {$i<100} {incr i} {
  incr x
  puts "$x [expr 0.3*[nrand] + 3]"
}

for {set i 0} {$i<200} {incr i} {
  incr x
  if {$i != 100} {puts "$x 0"}\
  else {puts "$x 2"}
}

for {set i 0} {$i<200} {incr i} {
  incr x
  set r [nrand]
  if {$i < 100} {puts "$x [expr $i/100.0]"}\
  else {puts "$x [expr 1+0.02*[nrand]]"}
}

for {set i 0} {$i<400} {incr i} {
  incr x
  set r [nrand]
  set y [expr sin(2*3.1415926*$x/100) + 0.5*$r]
  puts "$x $y"
}
